### ISSUE TITLE
White Screen after starting

### ISSUE THREAD

**Issue by TraxTRL** [Dev-Environments/VScode#1]
After the "Please wait" loading text, I get a white screen and nothing happens then. Please fix asap, ty!
> Installed App Version: 1.0.1

### System Information

[**Device**]
> Device: google Pixel 6 Pro
> Model: Pixel 6 Pro
> Manufacturer: Google
> Brand: google
> Display: 1440x3120

[**Hardware**]
> CPU Cores: 8
> Network: WiFi

[**Software**]
> OS: Android
> Version: 13
> SDK Version: 33

**Comment by TraxTRL** [comment]
nvm just received an answer on your play store page, thank you for that quick reply :)

**Comment by Dev-Environments** [comment]
We fixed this issue and today we will Update our app to v1.0.2
