### ISSUE TITLE
Live Server on VSCode for Android

### ISSUE THREAD

**Issue by BarniGr1** [Dev-Environments/VScode#12]
i want to use the App, VS Code for Android, on my tablet, Samsung Galaxy Tab S6.
I am trying to work on an Html file, and use the extension Live Server, to see my content on my tablet browser.
Unfortunately i only get a white page saying "not found."
Can you point me in the right direction please to solve my problem?
My OS is Android 12

**Comment by ShivaShirsath** [comment]
Use CodeSwing extension, search word as it is without any space.

**Comment by BarniGr1** [comment]
Thanks for the reply. I will look into it.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Dev-Environments/VScode/issues/12#event-11489516458

@Dev-Environments, how can this be [completed](https://github.com/Dev-Environments/VScode/issues?q=is%3Aissue+is%3Aclosed+reason%3Acompleted) when the last commit was 9 months ago? [^1]

[^1]: https://github.com/Dev-Environments/VScode/commits/main/?since=2023-04-06&until=2024-01-15

**Comment by Dev-Environments** [comment]
> Hi @RokeJulianLockhart, because this repo exists only to Report Bugs/issues. Thanks
