### ISSUE TITLE
[Bug]: Unable to install PHP

### ISSUE THREAD

**Issue by devhammed** [Dev-Environments/VScode#14]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Platform Information

- Platform: Android Mobile
- Model: Nokia X20
- Android --version: v13
- Architecture: arm64-v8a, armeabi-v7a, armeabi
- VScode App version: 1.0.4

### Steps to Reproduce

1. Open VS Code
2. Wait for the installation 
3. Then update the APT repository using: **apt update**
4. Then upgrade new packages: **apt upgrade**
5. Then install PHP: **apt install php**

### Expected

It would throw cross device link error.

### Actual

PHP should be installed.

### Alert Dialog

No

### Screenshot/Video

![Screenshot_20230507-102712](https://user-images.githubusercontent.com/22827908/236669574-76b2e3b2-c4da-4bc6-9533-8196966a5f8d.png)

### Does this issue happen in Previous Version or You a new user?

- [X] I tried everything but same issue.
- [ ] I cannot Clearing app data because i am Old user.

### Notes

I might have to request a refund if PHP can work on this.

**Comment by Dev-Environments** [comment]
> Exciting update v1.0.6! Now, both `php` and `composer` come pre-installed with additional assets, making the setup process smoother and eliminating the need for manual configuration. Happy coding! 🚀

**Comment by Dev-Environments** [comment]
> However, due to considerations regarding Assets size and individual user needs, we've opted not to include these environments as pre-installed assets. Instead, we've provided a streamlined method for users to install their desired environments based on their requirements.

> Rest assured, you can easily set up ```PHP``` environments by following the instructions provided in the app README.md file.
