### ISSUE TITLE
[Bug]: Composer kurulmuyor dpkg eror 1 hatası veriyor 

### ISSUE THREAD

**Issue by derebey278** [Dev-Environments/VScode#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Platform Information

- Platform:
- Model:
- Android --version:
- Architecture:
- VScode App version:

### Steps to Reproduce

1. 
2.

### Expected

Composer yuklenilebilir halae gelmelidir 

### Actual

Yok

### Alert Dialog

Yok

### Screenshot/Video

Yok

### Does this issue happen in Previous Version or You a new user?

- [X] #27
- [X] I cannot Clearing app data because i am Old user.

### Notes

Acilen çözülmesi gerekir 2 ay oldu alalı kullanamıyorum

**Comment by Dev-Environments** [comment]
Please tell me where dpkg error occured. Provide us a code

**Comment by Dev-Environments** [comment]
> Exciting update v1.0.6! Now, both `php` and `composer` come pre-installed with additional assets, making the setup process smoother and eliminating the need for manual configuration. Happy coding! 🚀

**Comment by Dev-Environments** [comment]
> However, due to considerations regarding Assets size and individual user needs, we've opted not to include these environments as pre-installed assets. Instead, we've provided a streamlined method for users to install their desired environments based on their requirements.

> Rest assured, you can easily set up ```PHP``` with ```compose``` environments by following the instructions provided in the app README.md file.

**Comment by derebey278** [comment]
Uygulama hiçbir yerde yok o nasıl olacak nasıl indirecem

29 Oca 2024 Pzt 14:31 tarihinde Dev-Environments ***@***.***>
şunu yazdı:

**Comment by Dev-Environments** [comment]
@derebey278 App is back Now: Check-Out this issue: https://github.com/Dev-Environments/Deleted-Issues/issues/13

**Comment by derebey278** [comment]
Ben bunu 1 kere aldım neden 1 kez daha satın alacam buju açıklayın ozaman
200tl ye almıştım ozaman paramı geri verin

29 Oca 2024 Pzt 15:04 tarihinde Dev-Environments ***@***.***>
şunu yazdı:

**Comment by Dev-Environments** [comment]
sir Fill-Up this form. vscodeform.dev-environments.com . Then you will get
Free Promo code

**Comment by derebey278** [comment]
Gönderdim

29 Oca 2024 Pzt 21:23 tarihinde Dev-Environments ***@***.***>
şunu yazdı:

> sir Fill-Up this form. vscodeform.dev-environments.com . Then you will
> get
> Free Promo code
>
