### ISSUE TITLE
running js code

### ISSUE THREAD

**Issue by AriCohelo** [Dev-Environments/VScode#17]
Hi, I'm trying to run javascript code white the "code runner" extension in android but iI get "node not found". Is there a way to run js code?
thanks

**Comment by Dev-Environments** [comment]
> Good news v1.0.6! Starting now, Node.js come pre-installed along with other assets, eliminating the need for manual setup.
> Rest assured, you can easily set up ```npm``` by following the instructions provided in the app README.md file.
