### ISSUE TITLE
How i can run my code

### ISSUE THREAD

**Issue by JustineBautista** [Dev-Environments/VScode#18]
I can't run the code like in pc on android its not supported to run

**Comment by israel010** [comment]
Same question.

**Comment by Dev-Environments** [comment]
If you Want to run code using Terminal Then you can open Terminal in Git folder which is located in root user home Directory. you can Go to this folder using `cd /root/Git`

**Comment by Dev-Environments** [comment]
Check-out this issue: https://github.com/Dev-Environments/VScode/issues/22#issuecomment-1892352540
