### ISSUE TITLE
Selection menu gone

### ISSUE THREAD

**Issue by KdntNinja** [Dev-Environments/VScode#20]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Platform Information

- Platform: Android
- Model: Samsung a70
- Android --version: 11
- Architecture:
- VScode App version: 1.0.4

### Steps to Reproduce

1. 
2.

### Expected

The search/selection menu in the top left should be there to select options

### Actual

It isn't there and I can't create a new file or do much in general

### Screenshot/Video

![Screenshot_20230518-080229_VScode](https://github.com/Dev-Environments/VScode/assets/116434277/216c46db-6aeb-4747-9dd8-9c472db2893f)

### Does this issue happen in Previous Version or You a new user?

- [X] I tried everything but same issue.
- [ ] I cannot Clearing app data because i am Old user.

**Comment by Dev-Environments** [comment]
That's not a bug/issue. You need to press and then hold a little bit blank place under extensions tab. then you see a list where you can show/hide menu tab. Like this 
![Screenshot from 2023-05-31 13-38-48](https://github.com/Dev-Environments/VScode/assets/124514686/8aa2a376-65ea-404a-ac7e-c2c7114b297e)

**Comment by KdntNinja** [comment]
Thank you
