### ISSUE TITLE
[Bug]: no abre error y el los archivos.solo carpetas vacias

### ISSUE THREAD

**Issue by Juudpro** [Dev-Environments/VScode#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Platform Information

- Platform:
- Model:huawei y5 2017  mya-l03
- Android --version:6.0
- Architecture:arm65-v80
- VScode App version:1.0.3

### Steps to Reproduce

1. Open vscode
2.install assets
3.veryfy assets
4.error box

### Expected

Mire la data y las carpetas estan vacias

### Actual

Se cierra por error de assets

### Alert Dialog

Error asset no encontrados

### Screenshot/Video

![Screenshot_2023-05-29-18-19-36](https://github.com/Dev-Environments/VScode/assets/134902336/d615ce42-6529-4f68-a789-2d59af51cc95)
![Screenshot_2023-05-29-18-19-36](https://github.com/Dev-Environments/VScode/assets/134902336/066052a9-b68f-4dee-943b-767390fd5ca5)
Imagen de error

### Does this issue happen in Previous Version or You a new user?

- [X] I tried everything but same issue.
- [X] I cannot Clearing app data because i am Old user.

**Comment by Dev-Environments** [comment]
Are you using a Real android Device or Virtual. If you are using a Virtual then on some type of virtual devices this issue occurs. e.g (App cloning, in Parallel Apps, Virtual Android in Android based apps like Redfinger and Virtual Android. etc......)
