### ISSUE TITLE
python pip command does not work

### ISSUE THREAD

**Issue by datacorner** [Dev-Environments/VScode#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Platform Information

- Platform: android
- Model: lenovo tab 11 pro
- Android --version: 11
- Architecture:
- VScode App version:

### Steps to Reproduce

1. run pip or python3 -m pip in the terminal
2.

### Expected

OSError ...

### Actual

impossible to add any python package

### Does this issue happen in Previous Version or You a new user?

- [X] I tried everything but same issue.
- [ ] I cannot Clearing app data because i am Old user.

**Comment by AlicanAKCA** [comment]
Any suggestion or solution?

**Comment by PCCAG** [comment]
Iam also. how to sloute it

**Comment by sidney-passos** [comment]
I see two problems in a big one: 1) You must install Java JVM and/or JRE and configure it, then compile the module pyjnius;  2) Then pip will throw a different exception, caused by failing executing 'Context = autoclass("android.content.Context")'.

Android 13 does not permit access to the Android folder anymore. This is the point where I can't go further.

Could be, of course, a bad Java configuration.

**Comment by brukberhane** [comment]
For anyone still looking for a solution for this. I found that adding an environment variable like so: `export ANDROID_DATA=anything` gets pip to work normally again. I found this solution at [this](https://stackoverflow.com/questions/73381766/cannot-use-the-pip-command-on-termux-ubunty-says-oserror-cant-fint-path-to-a) link

**Comment by Dev-Environments** [comment]
I will do a Proper Research on it and get back to you with solution.

**Comment by Dev-Environments** [comment]
>Good news v1.0.6! Starting now, both ```python3``` & ```pip3``` come pre-installed along with other assets, eliminating the need for manual Python setup

**Comment by Dev-Environments** [comment]
> However, due to considerations regarding Assets size and individual user needs, we've opted not to include these environments as pre-installed assets. Instead, we've provided a streamlined method for users to install their desired environments based on their requirements.

> Rest assured, you can easily set up ```Python``` with ```Pip3``` environments by following the instructions provided in the app README.md file.
> just run ```setupPython3Environment``` in integrated Terminal. It will automatically setup everything.
