### ISSUE TITLE
[Feat]: HTTPS Secure Connection

### ISSUE THREAD

**Issue by theomgdev** [Dev-Environments/VScode#26]
## What is your suggestion?
I want reach my server from my PC with permissions such as copy to clipboard etc. And it comes with secure connection. Please add a secure SSL supported connection over the port 443 or so.
## Why do you want this feature?
To use clipboard from my PC, upload files etc. More permission
## Are there any workarounds to get this functionality today?
I don't know but there should be a way to serve code-server to the port 443 as a secure connection

**Comment by Dev-Environments** [comment]
if you want to use your Android VScode from PC using browser then you can do like that. 
Follow the Steps:
1. Find IP Address of your device. Go to Settings->About->Status information->IP Address 100.78.138.100
2. Go to your desktop Browser and type http://your-ip-address:8080. Like that http://100.78.138.100:8080

**Comment by Dev-Environments** [comment]
Please use ngrok for that
