### ISSUE TITLE
Support 32 Bit Phone?

### ISSUE THREAD

**Issue by TreNzol** [Dev-Environments/VScode#35]
Please answer

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Dev-Environments/VScode/issues/35#issue-1759223185

@TreNzol, which architecture, specifically?

**Comment by Heritage-XioN** [comment]
Is it compatible for this 32bit device
Samsung a13 lte
PLATFORM OS - Android 12, upgradable to Android 13, One UI 5.1
Chipset - Exynos 850 (8nm)
CPUOcta-core (4x2.0 GHz 
Cortex-A55 & 4x2.0 GHz
 Cortex-A55)GPUMali-G52

**Comment by gbraad** [comment]
several devices from Samsung run in 32bit mode. you could try to use Project Treble and install AOSP rom that support full 64bit. you have a 4Gb or 6Gb model? I believe the former, as 64bit does not offer much benefits in that case. also less and less distros offer a non-64bit userspace. here, Ubuntu is used as aarch64

**Comment by Dev-Environments** [comment]
It supports but 32/64 bit architecture isn't the problem. Actually Device Resources matters. I Tested on 2GB ram devices lilke Samsung J4 and it worked but loading takes little bit more time. Thanks
