### ISSUE TITLE
[Bug]: Removed from Play Store

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Dev-Environments/VScode#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Platform Information

- Platform:
- Model:
- Android --version:
- Architecture:
- VScode App version:

### Steps to Reproduce

1. 
2.

### Does this issue happen in Previous Version or You a new user?

- [ ] I tried everything but same issue.
- [ ] I cannot Clearing app data because i am Old user.

### Notes

https://github.com/microsoft/vscode/issues/182605#issue-1711594385

**Comment by Dev-Environments** [comment]
App is back NOW checkout the link https://play.google.com/store/apps/details?id=dev.environment.VScode_PaidR1
We are providing a way to get this app for free if you already paid for it. then must check this https://vscodeform.dev-environments.com
And Thanks for your Patience.
