### ISSUE TITLE
[Bug]: Crashes on bluetooth

### ISSUE THREAD

**Issue by joshnajera** [Dev-Environments/VScode#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Platform Information

- Platform:
- Model:
- Android --version:
- Architecture:
- VScode App version:

### Steps to Reproduce

1. Connect bluetooth keyboard
2. Open VSCode
3. Disconnect bluetooth keyboard

OR
1. Disconnected bluetooth keyboard
2. Open VSCode
3. Connect bluetooth keyboard

### Expected

No crash

### Actual

Crash

### Alert Dialog

No

### Does this issue happen in Previous Version or You a new user?

- [ ] I tried everything but same issue.
- [ ] I cannot Clearing app data because i am Old user.

**Comment by derebey278** [comment]
Hocam vscode ile termux dizindeki dosyalra nasıl erişebiliriz

**Comment by joshnajera** [comment]
> Hocam vscode ile termux dizindeki dosyalra nasıl erişebiliriz

This is not the place to ask. Create another separate issue.

**Comment by Dev-Environments** [comment]
> Hocam vscode ile termux dizindeki dosyalra nasıl erişebiliriz

Yes, you are right  **joshnajera** & This App (`VScode for Android`) is not based on Termux. By the way Bluetooth Crash is fixed and we are working on other bugs as well So we will launch new Release with this & other bug fix++.

**Comment by derebey278** [comment]
Hocam benim terminal hata veriyor dpkg eror 1 hatası

17 Nis 2023 Pzt 18:30 tarihinde Dev-Environments ***@***.***>
şunu yazdı:

**Comment by Dev-Environments** [comment]
VScode Crush on Connect/Disconnect Bluetooth Devices issue Fixed & Released in **VScode v1.0.4**

**Comment by derebey278** [comment]
my terminal gives dpkg error 1 Fixes the problem

21 Nis 2023 Cum 11:17 tarihinde Dev-Environments ***@***.***>
şunu yazdı:
