### ISSUE TITLE
What is now about people that paid for this app?

### ISSUE THREAD

**Issue by Sedrowow** [Dev-Environments/VScode#40]
Will there be a reupload that is copyright complaint, or is there gonna be a refund?

**Comment by fet2002fr** [comment]
I don't understand Google responsibility on this. We pay thru theirs platform and get abondonned

**Comment by RokeJulianLockhart** [comment]
https://github.com/Dev-Environments/VScode/issues/39#issue-1788228649

**Comment by Dev-Environments** [comment]
App is back NOW checkout the link https://play.google.com/store/apps/details?id=dev.environment.VScode_PaidR1
We are providing a way to get this app for free if you already paid for it. then must check this https://vscodeform.dev-environments.com
And Thanks for your Patience.
