### ISSUE TITLE
[Bug]: Paid version here... Is a PlayStore ban? is a team issue? or is it the end?

### ISSUE THREAD

**Issue by hernand0** [Dev-Environments/VScode#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Platform Information

- Platform:
- Model:
- Android --version:
- Architecture:
- VScode App version:

### Steps to Reproduce

1. 
2.

### Expected

.

### Actual

.

### Does this issue happen in Previous Version or You a new user?

- [ ] I tried everything but same issue.
- [ ] I cannot Clearing app data because i am Old user.

**Comment by RokeJulianLockhart** [comment]
https://github.com/Dev-Environments/VScode/issues/39#issue-1788228649

**Comment by Dev-Environments** [comment]
App is back NOW checkout the link https://play.google.com/store/apps/details?id=dev.environment.VScode_PaidR1
We are providing a way to get this app for free if you already paid for it. then must check this https://vscodeform.dev-environments.com
And Thanks for your Patience.
