### ISSUE TITLE
Refund?

### ISSUE THREAD

**Issue by Sgt-Foley** [Dev-Environments/VScode#42]

**Comment by Dev-Environments** [comment]
**We are really sorry but We are working on that. Thank you**

**Comment by Dev-Environments** [comment]
App is back NOW checkout the link https://play.google.com/store/apps/details?id=dev.environment.VScode_PaidR1
We are providing a way to get this app for free if you already paid for it. then must check this https://vscodeform.dev-environments.com
And Thanks for your Patience.
