### ISSUE TITLE
[Feat]: 

### ISSUE THREAD

**Issue by OKgmr** [Dev-Environments/VScode#43]
## What is your suggestion?
Make simple UI ok please don't make a complex make beautiful and clean

**Comment by Dev-Environments** [comment]
Thank for your Suggestion. We appreciate that.

 **VScode for Android** App is back NOW checkout the link https://play.google.com/store/apps/details?id=dev.environment.VScode_PaidR1
We are providing a way to get this app for free if you already paid for it. then must check this https://vscodeform.dev-environments.com
And Thanks for your Patience.
