### ISSUE TITLE
[Feat]: Publish to an F-Droid repository.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Dev-Environments/VScode#44]
## What is your suggestion?

This application should be published to [`F-Droid.org/packages`](https://f-droid.org/en/packages/) as [the documentation](https://f-droid.org/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included) states, because [a search](https://search.f-droid.org/?q=Visual+Studio+Code&lang=en) returns 0 results.

## Why do you want this feature?

So that I can utilize your application without the Play Store installed.

## Are there any workarounds to get this functionality today?

1. #### GitHub CI + Obtanium

   Unfortunately, not even that is available, per https://github.com/Dev-Environments/VScode/issues/12#issuecomment-1893910744.

1. #### Self-Hosted Repository

   [Documentation](https://f-droid.org/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included) states:

   > You can also [set up your own repo](https://f-droid.org/docs/FAQ_-_App_Developers/#Can_I_run_my_own_app_repo) and distribute apps yourself, outside of the F-Droid.org repo.

**Comment by Dev-Environments** [comment]
Thanks but we can't do that if you wanna give any suggestion then feel free to give. if you wanna use that app check out the link https://play.google.com/store/apps/details?id=dev.environment.VScode_PaidR1.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Dev-Environments/VScode/issues/44#issuecomment-1890361820

@Dev-Environments, why not? Bitwarden runs their own repository, as an example.
