### ISSUE TITLE
[Bug]:Python interpreter not working 

### ISSUE THREAD

**Issue by johann-ui** [Dev-Environments/VScode#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Platform Information

- Platform: Android mobile
- Model: Tecno Camon 20 
- Android --version: 13
- Architecture: Helio G85
- VScode App version:  1.81.1

### Steps to Reproduce

1. Open vscode install python extension 
2.Run python code

### Expected

The expectation is that vscode will work when you hit run on the python code and execute it as it should 

### Actual

Currently vscode does not execute the python code and sends an error that it does not have the interpreter, I installed a python interpreter on my cell phone and I still get that there is no python interpreter 

### Alert Dialog

If I found a dialog box that tells me that there is no python interpreter I can't get it 

### Screenshot/Video

![Screenshot_20240119-093130](https://github.com/Dev-Environments/VScode/assets/76263459/62c6028e-3498-4bb6-93d8-6e498d5ec808)

![Screenshot_20240118-211745](https://github.com/Dev-Environments/VScode/assets/76263459/8bc06f62-23ef-48be-b7b5-1440828c5a2b)

### Does this issue happen in Previous Version or You a new user?

- [X] I tried everything but same issue.
- [ ] I cannot Clearing app data because i am Old user.

### Notes

If a python interpreter could be added to vscode, there is internally where the user does not have to download and install interpreters externally, so that when one is using vscode one can execute The code without having to do extra things outside

If by chance the interpreter cannot be added to vscode, have a way to implement it yourself that is not so extensive that it is easy to implement, and make video tutorials that help with Problems similar to this one and that users can easily get them through links or on YouTube, that would make it much easier.

**Comment by Dev-Environments** [comment]
> Step 1: Run this command ```sudo apt-get update```
> Step 2: ```sudo apt-get install python3 -y```
> Step 3: Check is Python3 is installed correctly ```python3 --version```
> Step 4: Select Python interpreter.

>Good news v1.0.6! Starting now, both ```python3``` & ```pip3``` come pre-installed along with other assets, eliminating the need for manual Python setup

**Comment by Dev-Environments** [comment]
> However, due to considerations regarding Assets size and individual user needs, we've opted not to include these environments as pre-installed assets. Instead, we've provided a streamlined method for users to install their desired environments based on their requirements.

> Rest assured, you can easily set up ```Python``` with ```Pip3``` environments by following the instructions provided in the app README.md file.
