### ISSUE TITLE
i[Bug]:  I can not plot with matplotlib on python.

### ISSUE THREAD

**Issue by Yesid901208** [Dev-Environments/VScode#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Platform Information

- Platform: android
- Model: galaxy tan s7 fe
- Android --version: 13
- Architecture: arm
- VScode App version: 1.0.3

### Steps to Reproduce

1. Install python
2. run example code

import numpy as np
#ANDROID_DATA=anything ( this is for using pip install)

import matplotlib.pyplot as plt

fig, ax = plt.subplots()

fruits = ['apple', 'blueberry', 'cherry', 'orange']
counts = [40, 100, 30, 55]
bar_labels = ['red', 'blue', '_red', 'orange']
bar_colors = ['tab:red', 'tab:blue', 'tab:red', 'tab:orange']

ax.bar(fruits, counts, label=bar_labels, color=bar_colors)

ax.set_ylabel('fruit supply')
ax.set_title('Fruit supply by kind and color')
ax.legend(title='Fruit color')

#plt.show()
plt.show(block=True)

### Expected

![Screenshot_20230419_175606_VScode](https://user-images.githubusercontent.com/8410227/233132456-1653da13-ca46-44ac-b11e-2d25c69751dc.jpg)

### Does this issue happen in Previous Version or You a new user?

- [X] I tried everything but same issue.
- [ ] I cannot Clearing app data because i am Old user.

**Comment by Dev-Environments** [comment]
> Good news v1.0.6! Starting now, both `python3` and `pip3` come pre-installed along with other assets, eliminating the need for manual Python setup.

> However, please note that "VScode for Android" currently doesn't support GUI windows displayed during the debugging of Matplotlib. But fear not! You can still visualize and control your graph by generating an HTML file of the graph output. Simply open the HTML file in your browser or utilize codeSwing within the "VScode for Android" app.

> For instance, you can achieve this with the following code:

```python
import numpy as np
import matplotlib.pyplot as plt
import mpld3

fig, ax = plt.subplots()

fruits = ['apple', 'blueberry', 'cherry', 'orange']
counts = [40, 100, 30, 55]
bar_labels = ['red', 'blue', 'red', 'orange']
bar_colors = ['tab:red', 'tab:blue', 'tab:red', 'tab:orange']

ax.bar(fruits, counts, label=bar_labels, color=bar_colors)

ax.set_ylabel('fruit supply')
ax.set_title('Fruit supply by kind and color')
ax.legend(title='Fruit color')

# Convert the Matplotlib plot to an interactive HTML plot
html_plot = mpld3.fig_to_html(fig)

# Save the HTML plot to a file or serve it using a web server
with open("fruit_supply_plot.html", "w") as html_file:
    html_file.write(html_plot)

# Alternatively, if you are using a Jupyter Notebook, you can display the plot directly:
# mpld3.display(fig)
```

This code snippet allows you to generate an interactive HTML plot that you can view and control effortlessly. Enjoy coding with "VScode for Android"! 🚀

**Comment by Dev-Environments** [comment]
> However, due to considerations regarding Assets size and individual user needs, we've opted not to include these environments as pre-installed assets. Instead, we've provided a streamlined method for users to install their desired environments based on their requirements.

> Rest assured, you can easily set up Python with Pip3 environments by following the instructions provided in the app README.md file.
