### ISSUE TITLE
Atualização 

### ISSUE THREAD

**Issue by Pk-silva** [Dev-Environments/VScode#54]
## What is your suggestion?
Eu comprei uma versão anterior custou 17 e alguns centavos e depois ele sumiu da play store agora observei que ele está de volta porém com a logo diferente e com um preço bem mais bem maior e como eu paguei o outro eu quero saber se vocês vão liberar para mim atualização ou essa versão que eu não sei como é que vai funcionar porque não aparece para atualizar mas eu paguei eu utilizei muito pouco então esse é o motivo pelo qual eu entrei em contato[Feat]:

**Comment by Dev-Environments** [comment]
Solution's here Dev-Environments/Deleted-Issues#13
