### ISSUE TITLE
[Solved] [Bug]: Can't configure PHP

### ISSUE THREAD

**Issue by anonimo82** [Dev-Environments/VScode#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Platform Information

- Platform: Android mobile 
- Model: Samsung Galaxy S20 5G 
- Android --version: 13
- Architecture: Arm64
- VScode App version: 1.0.6

### Steps to Reproduce

1. Open a PHP file
2. Try to configure PHP executable path

### Expected

I should get an input field to enter the PHP command in

### Actual

Absolutely nothing 

### Screenshot/Video

![Screenshot_20240919_114847_VScode](https://github.com/user-attachments/assets/4b2628a2-0daa-40a8-9c8e-82f15b093cbb)
![Screenshot_20240919_114949_VScode](https://github.com/user-attachments/assets/c4793506-0470-48de-b127-c68cc325f6a3)

### Does this issue happen in Previous Version or You a new user?

- [x] I tried everything but same issue.
- [x] I cannot Clearing app data because i am Old user.

### Notes

It would suffice to enable editing the settings .json

**Comment by Anju023** [comment]
install this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by anonimo82** [comment]
I'm using Android, it doesn't use DLLs

**Comment by anonimo82** [comment]
Nevermind, the PHP installation was incomplete. 
I did a `dpkg --configure -a` and now everything works.

Thanks anyhow.
