### ISSUE TITLE
Live view

### ISSUE THREAD

**Issue by SanchoDev39** [Dev-Environments/VScode#66]
ADD ISSUE DESCRIPTION HERE

The option live view is not displaying anything it just stay in status loading ... 

Version: 1.85.1
Commit: 14633336
User Agent: Mozilla/5.0 (Android 14; Mobile; rv:125.0) Gecko/125.0 Firefox/125.0
Embedder: server-distro

**Comment by Dev-Environments** [comment]
Bug Fixed in app version v1.0.8. Update the App
