### ISSUE TITLE
[Bug]: Physical keyboard

### ISSUE THREAD

**Issue by Elemiu** [Dev-Environments/VScode#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Platform Information

- Platform: Android mobile
- Model: Lenovo Tab P12
- Android --version: v14
- Architecture: 
- VScode App version: 1.0.7

### Steps to Reproduce

1. connect a bluetooth keyboard to the tablet
2. open vscode
3. try to write something

### Expected

writing normally 

### Actual

the letters overlap when you write until you use space

### Screenshot/Video

https://github.com/user-attachments/assets/beec6f1d-7f29-47b8-9752-b4eb9f35ee7c

### Does this issue happen in Previous Version or You a new user?

- [X] I tried everything but same issue.
- [ ] I cannot Clearing app data because i am Old user.

**Comment by Dev-Environments** [comment]
Bug Fixed in app v1.0.8 and Try using View 1
