### ISSUE TITLE
[Feat]: pip for python 3

### ISSUE THREAD

**Issue by zihadttttttttttt** [Dev-Environments/VScode#9]
## What is your suggestion?
Please add pip for python 3 
## Why do you want this feature?
Pip for python 3 is very very useful to install module like kivy numpy
pandas
matplotlib
scikit-learn  etc 
## Are there any workarounds to get this functionality today?
I don't know of any workarounds

**Comment by escalantemura** [comment]
It's already installed after Python instalation. Although I couldn't make it work properly. Check it out with `pip3 -v` on the terminal.

**Comment by Dev-Environments** [comment]
>Good news v1.0.6! Starting now, both ```python3``` & ```pip3``` come pre-installed along with other assets, eliminating the need for manual Python setup

**Comment by Dev-Environments** [comment]
> However, due to considerations regarding Assets size and individual user needs, we've opted not to include these environments as pre-installed assets. Instead, we've provided a streamlined method for users to install their desired environments based on their requirements.

> Rest assured, you can easily set up Python with Pip3 environments by following the instructions provided in the app README.md file.
